# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6



# PARAMETROS DEPORTES
NIVEL_IMPLEMENTOS = 0.2
PUNTAJE_MINIMO = 0
RIESGO_ATLETISMO = 0.2
RIESGO_CICLISMO = 0.35
RIESGO_GIMNASIA = 0.3
RIESGO_NATACION = 0.25

PONDERADOR_ATLETISMO_VEL = 0.55
PONDERADOR_ATLETISMO_RES = 0.2
PONDERADOR_ATLETISMO_MORAL = 0.25

PONDERADOR_CICLISMO_VEL = 0.47
PONDERADOR_CICLISMO_RES = 0.36
PONDERADOR_CICLISMO_FLEX = 0.17

PONDERADOR_GIMNASIA_MORAL = 0.2
PONDERADOR_GIMNASIA_RES = 0.3
PONDERADOR_GIMNASIA_FLEX = 0.5

PONDERADOR_NATACION_VEL = 0.45
PONDERADOR_NATACION_RES = 0.3
PONDERADOR_NATACION_FLEX = 0.25

# PARAMETROS DEPORTISTAS
MAXIMO_HABILIDADES = 100
MINIMO_HABILIDADES = 0

# PARAMETROS DELEGACIONES
PUNTOS_ENTRENAMIENTO = 1
COSTO_IMPLEMENTOS = 150
COSTO_SANAR = 30
COSTO_ENTRENAR = 30

AUMENTO_EFECTIVIDAD_IMPLEMENTOS = 0.1
EXC_RESPETO_MEDALLA_WIN = 0.01
EXC_RESPETO_MEDALLA_LOSE = 0.02

MORAL_DEPORTISTA_MEDALLA_WIN = 20
MORAL_DEPORTISTA_MEDALLA_LOSE = 10

DINERO_DELEGACION_MEDALLA_WIN = 100
# PARAMETROS DELEGACION IEEESPARTA
IEEE_EXC_RESPETO_MIN = 0.4
IEEE_EXC_RESPETO_MAX = 0.8
IEEE_IMPL_DEPORTIVOS_MIN = 0.3
IEEE_IMPL_DEPORTIVOS_MAX = 0.7
IEEE_IMPL_MEDICOS_MIN = 0.2
IEEE_IMPL_MEDICOS_MAX = 0.6
IEEE_EFECTIVIDAD_ENTRENAMIENTO = 1.7

# PARAMETROS DELEGACION DCCROTONA
DCC_EXC_RESPETO_MIN = 0.3
DCC_EXC_RESPETO_MAX = 0.7
DCC_IMPL_DEPORTIVOS_MIN = 0.2
DCC_IMPL_DEPORTIVOS_MAX = 0.6
DCC_IMPL_MEDICOS_MIN = 0.4
DCC_IMPL_MEDICOS_MAX = 0.8

